global:
  postgresql:
    auth:
      postgresPassword: trino_demo_password
      database: trino_demo
      username: trino_demo_user
      password: trino_demo_password

primary:
  initdb:
    scripts:
      seed.sql: |
        CREATE TABLE IF NOT EXISTS users(
          id BIGINT GENERATED ALWAYS AS IDENTITY,
          PRIMARY KEY(id),
          hash_firstname TEXT NOT NULL,
          hash_lastname TEXT NOT NULL,
          gender VARCHAR(6) NOT NULL CHECK (gender IN ('male', 'female'))
        );
        INSERT INTO users(hash_firstname, hash_lastname, gender)
        SELECT md5(RANDOM()::TEXT), md5(RANDOM()::TEXT), CASE WHEN RANDOM() < 0.5 THEN 'male' ELSE 'female' END FROM generate_series(1, 10000);
